# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d27ea722607019f53b3ee5ce8cf74803fd616d6b242db10bb22a0dea3ba1ef541127a2cd077f9b4577c253b1785d0174f31c4cda42021ac5f11f3085eb6cc85

test:
  secret_key_base: 9636efe3187e781e7388fecd5f24891f337915cd6056f3baff5dea3339642e021f956e7e92d55ac87d479a1e4e1afa6fa8c2f1dd71c3d5bedc8014d6893d07ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
